on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-clippy.yml
  pull_request:
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-clippy.yml
name: cargo clippy
jobs:
  cargoclippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags: [
          "",
          "--all-features",
          "--no-default-features --features ''",
          "--no-default-features --features 'pcsc'",
          "--no-default-features --features 'tracing'",
          "--no-default-features --features 'std'",
        ]
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpcsclite-dev
        shell: bash
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Run clippy
        run: cargo clippy ${{ matrix.flags }} --tests -- -D warnings
      - name: Cargo check --release
        run: cargo check --release
