on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-doc.yml
  pull_request:
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-doc.yml
permissions:
  packages: read
  contents: read
name: cargo doc
jobs:
  cargodoc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpcsclite-dev
        shell: bash
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.toml') }}
      - name: Run cargo doc
        run: |
          cargo doc --all-features --no-deps
        shell: bash
